on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: godsenal/github-timestamp-tag@v0.0.1
        with:
          prefix: "test-"
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(`The previous tag is: ${{ steps.foo.outputs.previousTag }}`);
            console.log(`The current tag is: ${{ steps.foo.outputs.currentTag }}`);
            console.log(`The release note is: ${{ steps.foo.outputs.releaseNote }}`);
